@startuml
class CleanningRoomController {
    + washingMachineController : WashingMachineController
    + dishWasherController : DishWasherController
    + kitchenPorterController : KitchenPorterController
}
@enduml
