@startuml
!include .\\Form1.plantuml
!include .\\Form1.Designer.plantuml
!include .\\Program.plantuml
!include .\\ClientGeneratorController.plantuml
!include .\\Controller.plantuml
!include .\\GroupClientController.plantuml
!include .\\ScenarioController.plantuml
!include .\\ViewController.plantuml
!include .\\Clock.plantuml
!include .\\ConstantGeneral.plantuml
!include .\\ConstantPosition.plantuml
!include .\\Enums.plantuml
!include .\\ISubject.plantuml
!include .\\Model.plantuml
!include .\\AssemblyInfo.plantuml
!include .\\Resources.Designer.plantuml
!include .\\Settings.Designer.plantuml
!include .\\IObserver.plantuml
!include .\\CleanningRoomController.plantuml
!include .\\DishWasherController.plantuml
!include .\\KitchenPorterController.plantuml
!include .\\WashingMachineController.plantuml
!include .\\DinnerRoomController.plantuml
!include .\\MaitreHotelController.plantuml
!include .\\SquareSupervisorController.plantuml
!include .\\TableController.plantuml
!include .\\WaiterController.plantuml
!include .\\KitchenAssitantController.plantuml
!include .\\KitchenController.plantuml
!include .\\MasterChefController.plantuml
!include .\\SectionChefController.plantuml
!include .\\DataBaseExchanger.plantuml
!include .\\RequestMapper.plantuml
!include .\\Client.plantuml
!include .\\DinnerRoom.plantuml
!include .\\GroupClient.plantuml
!include .\\Line.plantuml
!include .\\MaitreHotel.plantuml
!include .\\Square.plantuml
!include .\\SquareSupervisor.plantuml
!include .\\Table.plantuml
!include .\\Waiter.plantuml
!include .\\Command.plantuml
!include .\\Counter.plantuml
!include .\\GroupCommand.plantuml
!include .\\Ustensil.plantuml
!include .\\CleanningRoom.plantuml
!include .\\CookingRoom.plantuml
!include .\\DishWasher.plantuml
!include .\\Kitchen.plantuml
!include .\\KitchenPorter.plantuml
!include .\\MasterChef.plantuml
!include .\\SectionChef.plantuml
!include .\\StorageRoom.plantuml
!include .\\WashingMachine.plantuml
!include .\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.plantuml
!include .\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.plantuml
!include .\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.plantuml
@enduml
